[package]
name = "monad-load-balancer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.100"
env_logger = "0.11"
log = "0.4"

[dev-dependencies]
tokio-test = "0.4"